In [ ]:
!git clone https://github.com/HeYantong/MSSP6070-Yantong.git

Cloning into 'MSSP6070-Yantong'...
remote: Enumerating objects: 72, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 72 (delta 27), reused 6 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (72/72), 718.47 KiB | 1.07 MiB/s, done.
Resolving deltas: 100% (27/27), done.

In [ ]:
%cd /content/MSSP6070-Yantong

/content/MSSP6070-Yantong

In [ ]:
!ls

Adding_File_Structure.py  Assignments  data  README.md	WeeklyModules
aapl.csv  amzn.csv  fb.csv  goog.csv  nflx.csv

In [ ]:
!ls data

aapl.csv  amzn.csv  fb.csv  goog.csv  nflx.csv

In [ ]:
import pandas as pd

fb = pd.read_csv("data/fb.csv")
aapl = pd.read_csv("data/aapl.csv")
amzn = pd.read_csv("data/amzn.csv")
nflx = pd.read_csv("data/nflx.csv")
goog = pd.read_csv("data/goog.csv")

aapl.head()

         date      open      high       low     close    volume
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766

In [ ]:
fb["ticker"] = "FB"
aapl["ticker"] = "AAPL"
amzn["ticker"] = "AMZN"
nflx["ticker"] = "NFLX"
goog["ticker"] = "GOOG"

aapl.head()

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

In [ ]:
faang = pd.concat([fb, aapl, amzn, nflx, goog], ignore_index=True)

In [ ]:
faang.to_csv("data/faang.csv", index=False)

In [ ]:
faang["date"] = pd.to_datetime(faang["date"])
faang["volume"] = faang["volume"].astype(int)
faang = faang.sort_values(["date", "ticker"])

faang.nlargest(7, "volume")

          date      open      high       low     close     volume ticker
142 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
53  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
57  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
54  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
433 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
496 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
463 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [ ]:
melted = faang.melt(
    id_vars=["date", "ticker"]
)

melted.head()

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000